apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace_argo-workflows.yaml
- ingress_argo-workflows.yaml
- serviceaccount_argo-workflows-admin.yaml
- secret_argo-workflows-admin-token.yaml
- clusterrolebinding_argo-workflows-admin.yaml
