apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# namespace is fragile, because there is inconstency in namespace between ServiceAccount and ClusterRoleBinding in install.yaml
# it should work unless you want to use different namespace than argo-rollouts
namespace: argo-rollouts

resources:
- ./manifests
- https://github.com/argoproj/argo-rollouts/releases/download/v1.7.2/install.yaml
