apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-workflows

resources:
- ./manifests
- https://github.com/argoproj/argo-workflows/releases/download/v3.5.10/install.yaml
