apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-lab-apps
  namespace: argo-cd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argo-cd 
  source:
    repoURL: "https://github.com/flphvlck/argo-labs.git"
    path: argo-cd/examples/apps
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
