apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: example-app
  namespace: argo-cd
spec:
  project: default
  destination:
    name: kind-lab1
    namespace: example-app
  source:
    repoURL: "https://github.com/flphvlck/LFS256-code"
    path: argocd/example-app
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
  
