apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace_argo-cd.yaml
- clusterrolebinding_workaround-admin.yaml
- serviceacount_workaround-admin.yaml
- secret_workaround-admin-token.yaml
- ingress_argo-cd-server-http-ingress.yaml
- ingress_argo-cd-server-grpc-ingress.yaml
