apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
- ./manifests
- https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.12.3
- https://github.com/argoproj/argo-cd/manifests/namespace-install?ref=v2.12.3

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"
