apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
- ./manifests
- https://github.com/argoproj/argo-cd/manifests/crds?ref=v2.13.0-rc3
- https://github.com/argoproj/argo-cd/manifests/namespace-install?ref=v2.13.0-rc3

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"
  - name: argocd-cm
    behavior: merge
    literals:
      - application.instanceLabelKey=argocd.argoproj.io/instance
