apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-cd

resources:
- ./manifests
- https://github.com/argoproj/argo-cd/manifests/crds?ref=v3.0.16
- https://github.com/argoproj/argo-cd/manifests/namespace-install?ref=v3.0.16

configMapGenerator:
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure="true"
  - name: argocd-cm
    behavior: merge
    literals:
      - application.resourceTrackingMethod=annotation
